const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Json,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{emailInput: 0},
	{senhaInput: 0},
	{nomeUsuarioInput: 0},
	{loginBtn: 0},
	{registrarBtn: 0},
	{JSON_Auth: 0},
	{JSON_Resp: 0},
	{Browser: 0},
	{Array: 0},
	{JSON_Send: 0},
	{statusTXT: 0},
	{JSON_Read: 0},
	{Timer: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Touch: 0},
	{Audio: 0},
	{Family1: 0},
	{email: 0},
	{password: 0},
	{username: 0},
	{tokens: 0},
	{skins: 0},
	{nivel: 0},
	{logged: 0},
	{user_token: 0},
	{URL_DB: 0},
	{URL_SINGUP: 0},
	{URL_SINGIN: 0},
	{API_KEY: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	emailInput: class extends self.ITextInputInstance {},
	senhaInput: class extends self.ITextInputInstance {},
	nomeUsuarioInput: class extends self.ITextInputInstance {},
	loginBtn: class extends self.IButtonInstance {},
	registrarBtn: class extends self.IButtonInstance {},
	JSON_Auth: class extends self.IJSONInstance {},
	JSON_Resp: class extends self.IJSONInstance {},
	Browser: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	JSON_Send: class extends self.IJSONInstance {},
	statusTXT: class extends self.ITextInstance {},
	JSON_Read: class extends self.IJSONInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Family1: class extends self.ISpriteInstance {}
}