const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pathfinding.Acts.RegenerateMap,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Pathfinding.Exps.MovingAngle,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.Button.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{walking: 0},
	{lastDirection: 0},
	{Pathfinding: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Touch: 0},
	{Solid: 0},
	{Sprite2: 0},
	{Mouse: 0},
	{Tilemap2: 0},
	{Tilemap3: 0},
	{Tilemap4: 0},
	{Tilemap5: 0},
	{emailInput: 0},
	{senhaInput: 0},
	{nomeUsuarioInput: 0},
	{loginBtn: 0},
	{registrarBtn: 0},
	{Sprite3: 0},
	{JSON_Auth: 0},
	{AJAX: 0},
	{JSON_Read: 0},
	{JSON_Send: 0},
	{JSON_Resp: 0},
	{Array: 0},
	{Browser: 0},
	{Audio: 0},
	{statusTXT: 0},
	{Timer: 0},
	{Yoshi: 0},
	{Fundo: 0},
	{Text: 0},
	{Family1: 0},
	{Form: 0},
	{email: 0},
	{password: 0},
	{username: 0},
	{tokens: 0},
	{skins: 0},
	{nivel: 0},
	{logged: 0},
	{cenouras: 0},
	{user_token: 0},
	{URL_DB: 0},
	{URL_SINGUP: 0},
	{URL_SINGIN: 0},
	{API_KEY: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	Tilemap4: class extends self.ITilemapInstance {},
	Tilemap5: class extends self.ITilemapInstance {},
	emailInput: class extends self.ITextInputInstance {},
	senhaInput: class extends self.ITextInputInstance {},
	nomeUsuarioInput: class extends self.ITextInputInstance {},
	loginBtn: class extends self.IButtonInstance {},
	registrarBtn: class extends self.IButtonInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	JSON_Auth: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	JSON_Read: class extends self.IJSONInstance {},
	JSON_Send: class extends self.IJSONInstance {},
	JSON_Resp: class extends self.IJSONInstance {},
	Array: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	statusTXT: class extends self.ITextInstance {},
	Yoshi: class extends self.ISpriteInstance {},
	Fundo: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Family1: class extends self.ISpriteInstance {},
	Form: class extends self.ITextInputInstance {}
}